# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Live

on:
  push:
    branches:
      - deploy/live
  workflow_dispatch:

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'Live'
    environment:
      name: 'Live'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Publish
        run: dotnet publish -c Release -o dist

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cadburycremeeggquiz'
          slot-name: 'production'
          publish-profile: ${{ secrets.DEPLOY_Live }}
          package: dist
